<a href="https://colab.research.google.com/github/Davizin06/C11_Ciencia_De_Dados/blob/main/cap4_10_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

Criando um NumPy Array



In [ ]:
import numpy as np

##Criando um numpy array em cima de um vetor

arr = np.array([10,20,30,40,50,60])
print(arr)

#Propriedades do array
print(arr.size)
print(arr.ndim)
print(arr.shape)
print(type(arr))

##Criando np array de uma matriz 2 dimensoes

mtz = np.array([[ 10,20],[30,40],[50,60]])
print(mtz.size)
print(mtz.ndim)
print(mtz.shape)
print(type(arr))



[10 20 30 40 50 60]
6
1
(6,)
<class 'numpy.ndarray'>
6
2
(3, 2)
<class 'numpy.ndarray'>


**Funções pré-prontas para estruturar numpy arrays**

In [ ]:
#Ones
mtz = np.ones([5,5])
print(mtz)

#Zeros
arr = np.zeros([10])
print(arr.reshape([5,2])) ##Reshape para alterar a dimensao do array

#Arange
mtz = np.arange(2, 21, 2)

print(mtz.reshape(2,5))



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


**Operações entre numpy arrays**

In [ ]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([60,70,80,90,40])

print(arr1 + arr2)


#Concatenacao de array

arr3 = np.concatenate([arr1,arr2])
print(arr3)



[ 70  90 110 130  90]
[10 20 30 40 50 60 70 80 90 40]


**Numeros aleatrios**

In [ ]:
##Módulo random

arr = np.random.randint(10)
print(arr)


4
