Slicing no Numpy

In [ ]:
import numpy as np

In [ ]:
#Plantando a mesma semente aleatoria
np.random.seed(10)
# Estruturando uma matriz 3x3
mtz = np.random.randint(1, 99, 9).reshape(3, 3) #randomrandint para criar com numeros aleatorios e .reshape para transformar em matriz
print(mtz)

[[10 16 65]
 [29 90 94]
 [30  9 74]]


In [ ]:
# Extraindo apenas a segunda linha da matriz
print(mtz[1])

#Extraindo apenas a terceira coluna da matriz
print(mtz[:,2])

#Extraindo a matriz 2x2 no canto inferior direito da matriz
print(mtz[1:,0:2])


[29 90 94]
[65 94 74]
[[29 90]
 [30  9]]


CONDICIONAIS NO NUMPY

In [ ]:
print(mtz)

#Mostre apenas os elementos menores que 70
# print(mtz<70)
# print(mtz[mtz<70])

#Retorne apenas os numeros pares
print(mtz%2==0)
print(mtz[mtz%2==0])

[[10 16 65]
 [29 90 94]
 [30  9 74]]
[[ True  True False]
 [False  True  True]
 [ True False  True]]
[10 16 90 94 30 74]


ANÁLISE DE PADRÕES TEXTUAIS COM NUMPY

In [ ]:
arr = np.array(['Inatel', 'Casa Viva', 'ICC',
               'CDG', 'CSILab', 'RobotBulls'])
print(arr)

cond = np.char.find(arr,'a') >=0
#Submodulo de NumPy para trabalhar com texto: char
#Buscando qual texto aceita um padrão informado

arr = np.char.upper(arr)
print(np.char.find(arr,'a'))
print(cond)
print(arr[cond])


['Inatel' 'Casa Viva' 'ICC' 'CDG' 'CSILab' 'RobotBulls']
[-1 -1 -1 -1 -1 -1]
[ True  True False False  True False]
['INATEL' 'CASA VIVA' 'CSILAB']


COMO IMPORTAR DATASETS NO NUMPY

In [ ]:
dataset = np.loadtxt('space.csv', delimiter=';', dtype='str')
print(dataset)

[['\ufeffNum' 'Company Name' 'Location' ... 'Status Rocket' ' Cost'
  'Status Mission']
 ['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA' ...
  'StatusActive' '50.0 ' 'Success']
 ['1' 'CASC' 'Site 9401 (SLS-2) Jiuquan Satellite Launch Center China'
  ... 'StatusActive' '29.75 ' 'Success']
 ...
 ['4321' 'US Navy' 'LC-18A Cape Canaveral AFS Florida USA' ...
  'StatusRetired' '0' 'Failure']
 ['4322' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']
 ['4323' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']]


In [ ]:
#Extraindo as colunas do dataset

print(dataset[0,:])

#Extraindo o nome das empresas
print(np.unique(dataset[1:,1], return_counts='True'))

['\ufeffNum' 'Company Name' 'Location' 'Datum' 'Detail' 'Status Rocket'
 ' Cost' 'Status Mission']
(array(['AEB', 'AMBA', 'ASI', 'Arianespace', "Arm??e de l'Air",
       'Blue Origin', 'Boeing', 'CASC', 'CASIC', 'CECLES', 'CNES',
       'Douglas', 'EER', 'ESA', 'Eurockot', 'ExPace', 'Exos',
       'General Dynamics', 'IAI', 'ILS', 'IRGC', 'ISA', 'ISAS', 'ISRO',
       'JAXA', 'KARI', 'KCST', 'Khrunichev', 'Kosmotras', 'Land Launch',
       'Landspace', 'Lockheed', 'MHI', 'MITT', 'Martin Marietta', 'NASA',
       'Northrop', 'OKB-586', 'OneSpace', 'RAE', 'RVSN USSR',
       'Rocket Lab', 'Roscosmos', 'SRC', 'Sandia', 'Sea Launch', 'SpaceX',
       'Starsem', 'ULA', 'US Air Force', 'US Navy', 'UT', 'VKS RF',
       'Virgin Orbit', 'Yuzhmash', 'i-Space'], dtype='<U84'), array([   3,    8,    9,  279,    4,   12,  136,  251,    5,    4,    8,
          1,    1,   13,   13,   10,    4,  251,   11,   46,    1,   13,
         30,   76,    7,    3,    5,    1,   22,    7,    1,   79,   84,
   