In [ ]:
# EXERCICIO 1
import numpy as np

arr1 = np.ones(8)
arr2 = np.random.randint(0, 10, 8)

arr3 = arr1 + arr2

print(arr3)

soma_total = arr3.sum()
if soma_total >= 40:
    matriz_reshape = arr3.reshape(4, 2)
else:
    matriz_reshape = arr3.reshape(2, 4)

print(f"Soma total: {soma_total}")

print("Matriz reshape:\n", matriz_reshape)

[ 5.  3.  5.  8. 10.  7. 10.  4.]
Soma total: 52.0
Matriz reshape:
 [[ 5.  3.]
 [ 5.  8.]
 [10.  7.]
 [10.  4.]]


In [ ]:
# EXERCICIO 2
arr1_pares = np.arange(0, 52, 2)
arr2_pares = np.arange(100, 49, -2)

arr_concatenado = np.concatenate((arr1_pares, arr2_pares))

arr_ordenado = np.sort(arr_concatenado)
print("Arrays concatenados e ordenados:\n", arr_ordenado)

Arrays concatenados e ordenados:
 [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [11]:
# EXERCICIO 3

campo_minado = np.zeros([2, 2])

linha_bomba = np.random.randint(0, 2)
coluna_bomba = np.random.randint(0, 2)
campo_minado[linha_bomba, coluna_bomba] = 1

jogadas_corretas = 0

for tentativa in range(3):
    print(f"\nTentativa {tentativa + 1}/3")
    linha = int(input("Escolha a linha (0 ou 1): "))
    coluna = int(input("Escolha a coluna (0 ou 1): "))

    if campo_minado[linha, coluna] == 1:
        print("Perdeu!")
        break
    else:
        print("Continua..")
        jogadas_corretas += 1

    if jogadas_corretas == 3:
        print("Ganhou!")


Tentativa 1/3
Escolha a linha (0 ou 1): 0
Escolha a coluna (0 ou 1): 0
Perdeu!


In [ ]:
# EXERCICIO 4
mtz = np.zeros([3, 5])

linhas, colunas = mtz.shape
multiplicacao = linhas * colunas

print(f"Linhas: {linhas} | Colunas: {colunas}")
print(f"Total de elementos: {multiplicacao}")

if multiplicacao % 2 == 0:
    print("Esta matriz pode se tornar um vetor unidimensional com um número PAR de elementos.")
else:
    print("Esta matriz pode se tornar um vetor unidimensional com um número ÍMPAR de elementos.")

Linhas: 3 | Colunas: 5
Total de elementos: 15
Esta matriz pode se tornar um vetor unidimensional com um número ÍMPAR de elementos.


In [ ]:
# EXERCICIO 5

np.random.seed(10)

mtz_4x4 = np.random.randint(1, 51, [4, 4])
print("Matriz 4x4:\n", mtz_4x4)

media_colunas = mtz_4x4.mean(axis=0)
media_linhas = mtz_4x4.mean(axis=1)
print("\nMédia das colunas:", media_colunas)
print("Média das linhas:", media_linhas)

maior_media_colunas = media_colunas.max()
maior_media_linhas = media_linhas.max()
print("\nMaior média encontrada nas colunas:", maior_media_colunas)
print("Maior média encontrada nas linhas:", maior_media_linhas)

unicos, contagens = np.unique(mtz_4x4, return_counts=True)

print("\nQuantidade de aparições de cada número:")
for numero, contagem in zip(unicos, contagens):
    print(f"Número {numero}: {contagem} vez(es)")

condicao = contagens == 2
numeros_repetidos_duas_vezes = unicos[condicao]
print("\nNúmeros que aparecem exatamente 2 vezes na matriz:", numeros_repetidos_duas_vezes)

Matriz 4x4:
 [[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]

Média das colunas: [29.75 24.25 33.75 20.25]
Média das linhas: [16.   33.75 34.5  23.75]

Maior média encontrada nas colunas: 33.75
Maior média encontrada nas linhas: 34.5

Quantidade de aparições de cada número:
Número 1: 2 vez(es)
Número 9: 1 vez(es)
Número 10: 2 vez(es)
Número 16: 1 vez(es)
Número 26: 1 vez(es)
Número 29: 1 vez(es)
Número 30: 2 vez(es)
Número 37: 1 vez(es)
Número 41: 1 vez(es)
Número 43: 1 vez(es)
Número 49: 1 vez(es)
Número 50: 2 vez(es)

Números que aparecem exatamente 2 vezes na matriz: [ 1 10 30 50]
